# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
# pull_request:
#   branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: test
      run: |
        export SSH_ASKPASS=../ssh_passthrough.sh 
        export DISPLAY=:0
        eval `ssh-agent -s`
        echo -e "#\!/bin/bash\nread SECRET\necho \$SECRET" > $SSH_ASKPASS
        chmod 744 $SSH_ASKPASS
        (ssh-add - <<< "${{ secrets.AUTUMN_SSH_KEY }}") <<< "${{ secrets.AUTUMN_SSH_PASSPHRASE }}" 

    # Runs a set of commands using the runners shell
#   - name: Run a multi-line script
#     run: |
#       echo Add other actions to build,
#       echo test, and deploy your project.
